'first question
SELECT CUST.CUST_ID,CUST.CUST_FIRSTNAME, CUST.CUST_ADDRESS, ACT.ACC_NUMBER, COUNT(ACT.ACC_OWNER) AS TOTAL_ACCOUNT FROM CUSTOMER CUST
LEFT JOIN ACCOUNT ACT ON ACT.ACC_OWNER = CUST.CUST_ID;


'second question
SELECT CUST.CUST_FIRSTNAME, T.TRS_FROM_ACCOUNT AS SOURCE_ACCOUNT, TT.TRS_TO_ACCOUNT AS DEST_ACCOUNT, T.TRS_DATE, T.TRS_AMOUNT
FROM TRANSACTION_TRANSFER TT
LEFT JOIN TRANSACTION T ON T.TRS_ID=TT.TRS_ID
LEFT JOIN ACCOUNT ACT1 ON T.TRS_FROM_ACCOUNT=ACT1.ACC_NUMBER
LEFT JOIN ACCOUNT ACT2 ON TT.TRS_TO_ACCOUNT=ACT2.ACC_NUMBER
LEFT JOIN CUSTOMER CUST ON ACT1.ACC_OWNER=CUST.CUST_ID
ORDER BY ACT.ACC_NUMBER, T.TRS_DATE;
